version: "3.9"

services:
  # Backend Flask
  backend:
    build: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/popcorn
      - SECRET_KEY=supersecretkey
    depends_on:
      - db

  # Banco de dados PostgreSQL
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: popcorn
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Frontend Vue.js
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend

  # Proxy reverso Nginx
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
